sonar.organization=jgtamanini
sonar.projectKey=jgtamanini_C4Diagrams_frontend
sonar.projectName=C4Diagrams - Frontend

# Diretório com o código-fonte a ser analisado
sonar.sources=src

# Arquivos/pastas que não devem ser analisados
sonar.exclusions=node_modules/**,dist/**,build/**,**/*.config.js

sonar.sourceEncoding=UTF-8
