sonar.organization=jgtamanini
sonar.projectKey=jgtamanini_C4Diagrams_frontend
sonar.projectName=C4Diagrams - Frontend

sonar.sources=src

sonar.exclusions=node_modules/**,dist/**,build/**,**/*.config.js

sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.js
sonar.coverage.exclusions=src/**/*.test.jsx,src/**/*.test.js,src/test/**

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info