sonar.organization=jgtamanini
sonar.projectKey=jgtamanini_C4Diagrams_backend
sonar.projectName=C4Diagrams - Backend

sonar.sources=src

sonar.tests=tests

sonar.exclusions=node_modules/**,migrations/**

sonar.sourceEncoding=UTF-8
