sonar.organization=jgtamanini
sonar.projectKey=jgtamanini_C4Diagrams_backend
sonar.projectName=C4Diagrams - Backend

# Diretório com o código-fonte a ser analisado
sonar.sources=src

# Testes ficam em pasta separada (ainda vazia, mas já reservado o caminho)
sonar.tests=tests

# Arquivos/pastas que não devem ser analisados
sonar.exclusions=node_modules/**,migrations/**

sonar.sourceEncoding=UTF-8
